### ISSUE TITLE
Feature: builder factory i.e `FieldSuggestion.builder()`

### ISSUE THREAD

**Issue by g-scosta** [theiskaa/field_suggestion#26]
Hi, first I want to thank you for this library, it's the best of the kind that I found!

I'm needing to show a tooltip when user hovers the item in the suggestion list. This would be possible If we had an option to pass a wrapper to the item. 

Right now I'm doing this passing to the FieldSuggestion this parameter:
`Widget Function(int, Widget)? itemWrapper;`

and changed the itemBuilder inside _buildSuggestionBox to:
```
itemBuilder: (context, index) => widget.itemWrapper != null
                ? widget.itemWrapper!(index, suggestionListItem(index))
                : suggestionListItem(index),
```

I don't know if there is a better way to do this. If this could be added inside this library it would be great.

**Comment by theiskaa** [comment]
Hello, thank you!

Ya, that's a great idea, I will be thinking about it.
Are you satisfied with the result of `itemWrapper` property? However, could you please add a gif or screenshot so that I can fully understand the feature you want so maybe we can do it in other ways?

Thank you again ❤️

**Comment by g-scosta** [comment]
Thank you for your fast reply. 

I was satisfied with itemWrapper, but now I'm thinking in more use cases that it won't cover and that I'll need to add more customizations. 

I think a great way to cover all possible use cases would be providing an itemBuilder option (as in ListViews, etc). For example, now I'm needing to do a suggestion with image, title, subtitle, etc. I'll put a image of the suggestion below.

![image](https://user-images.githubusercontent.com/84533613/126801756-8b90e991-8be8-42a5-a902-581858cea69e.png)

If we could pass an itemBuilder I could do this easily and it would also cover the tooltip case that I mentioned above.

**Comment by theiskaa** [comment]
Exactly I thought `itemBuilder` would be a better solution than a wrapper.

**Comment by g-scosta** [comment]
I'm thinking how we could handle the onTap events from the items inside the itemBuilder. We could add custom events and manipulate the textEditingController inside the builder but I think we would miss the closeBox functionality. I couldn't figure out how to do this yet.

**Comment by theiskaa** [comment]
Ya ya lol, No worries, I'll be thinking about it. 
I hope I can complete the feature as soon as possible.

**Comment by g-scosta** [comment]
Take the time you need. I'll be using the code with my customizations while it's not available.

Just for you to know, the itemBuilder method that I'm using is a `Widget Function(BuildContext, int, dynamic)?`, where int is the index and dynamic is the matchers[index], I think this covers all possible use cases.

**Comment by theiskaa** [comment]
Okay, thank you for your time and contribution, I'll do it as soon as possible. 

It's gonna be an awesome feature 🎉

**Comment by theiskaa** [comment]
Hello! I'm done, so I opened [PR](https://github.com/theiskaa/field_suggestion/pull/27) and waiting for your review (But I can't request a review from you I don't know why)
So just check that [PR](https://github.com/theiskaa/field_suggestion/pull/27), test it, and tell me if it's the right thing for you. 

Thank you for your contribution and awesome idea ❤️

**Comment by g-scosta** [comment]
Great! I made a comment there, I think it needs just a quick fix and it'll be great! Thanks again for this great library!

**Comment by theiskaa** [comment]
Hey, @g-scosta feature is fully ready now. I commented on PR please check it ...

**Comment by g-scosta** [comment]
Hey @theiskaa , I've found a bug in this feature.

When I click on an item that was suggested I remove it from the suggestionList (to not find it again). The problem is that while the suggestionList is updated, the objectSuggestionsAsJson isn't, because the initState is not called again.

The solution that I found is to rebuild objectSuggestionAsJson inside _textListener if they're not the same length (I don't know if we need to check the equality of all the items, I couldn't think in an use case that it was necessary).

So part of the _textListener function is below

```
if (isObjList(widget.suggestionList)) {
        if (widget.suggestionList.length != objectSuggestionsAsJson.length) {
          objectSuggestionsAsJson =
              widget.suggestionList.map((e) => e.toJson().toString()).toList();
        }
        // At this time, `searchBy` must not be null.
        // Because renderObjList (which fill's matchers) must have [searchBy] properties,
        // to know which variable you wanna search by.
        if (widget.searchBy == null) {
          throw FlutterError(
            "If given suggestionList's runtimeType isn't List<String>, List<int> or List<double>. That means, you was gave a List which includes dart classes. So then [searchBy] can't be null.",
          );
        }
        matchers = renderObjList(
          widget.suggestionList,
          inputText,
          widget.searchBy,
        );
      }
```

**Comment by theiskaa** [comment]
Hey @g-scosta
Okay cool, Please fill in a new issue and I'll care about it.

**Comment by theiskaa** [comment]
Hey @g-scosta
Please see #29-Issue and #30-PR.
