### ISSUE TITLE
Cannot refresh state

### ISSUE THREAD

**Issue by theiskaa** [theiskaa/field_suggestion#29]
###  Bug Description:
When we try to remove an item from our suggestion list, then already opened suggestion box cannot understand that so it didn't update. 
However, FieldSuggestion's BoxController should have a refresh functionality to refresh widget after local changes.

Reported by: @g-scota

### To Reproduce
1. Make a field suggestion widget (by builder).
2. Add remove functionality to Suggestion Item. and try that functionality

**Comment by g-scosta** [comment]
Great! Thanks for the fast fix!

**Comment by theiskaa** [comment]
@g-scosta  You're welcome! Okay, then I'll merge it and release a new version 😄
