### ISSUE TITLE
Add custom matcher option

### ISSUE THREAD

**Issue by gcostaapps** [theiskaa/field_suggestion#34]
**Is your feature request related to a problem? Please describe.**
In current version the field is always searched based in contains method. But sometimes I need a more advanced search. (In my case I need to remove diacritics (accented characters) and compare just the begining of the words, that means that if search oe in the name Jhon Doe 0 results will be found, but Doe will return the result).

**Describe the solution you'd like**
A general solution would be passing a custom query matcher so the developer can pass any function (regex, custom functions, etc) that returns a boolean value if the matchers is to be included

**Additional context**
I've created an aditional parameter in FieldSuggestion called customMatcher and passed the value when the matchers are evaluated inside _textListener.

Ex:
```
final bool Function(dynamic, String)? customMatcher;

...

if (widget.customMatcher != null) {
        matchers = widget.suggestionList
            .where((item) => widget.customMatcher!(item, inputText))
            .toList();
      } else {
        matchers = widget.suggestionList.where((item) {
          // If we call toUperrCase on int or on double then we'll get error.
          // So that's why we check type of list and return suitable method.
          if (widget.suggestionList is List<int> ||
              widget.suggestionList is List<double>) {
            return item.toString().contains(inputText.toString());
          }
          return item.toUpperCase().contains(inputText.toUpperCase());
        }).toList();
      }
```

**Comment by theiskaa** [comment]
Hi @gcostaapps. First of all, thanks for great feature suggestion.

Yep true. We should provide a way where we could pass our custom sorting structure.
But, in your implementation, it won't work for other additional features. I'll think about that.

Thanks again for feature request.

**Comment by theiskaa** [comment]
Hello, @gcostaapps. I opened [Draft PR](https://github.com/theiskaa/field_suggestion/pull/35) to resolve the issue.
Basically, the feature is ready to use. I have to write tests and also documentation.

**Comment by gcostaapps** [comment]
Hi @theiskaa, I checked the PR and I think it's great!

**Comment by theiskaa** [comment]
Hello again @gcostaapps. The issue was resolved and the feature is ready now. You can start using it now.

**Comment by gcostaapps** [comment]
Great! I'm on vacation but I as soon as I get home I'll start using! Thanks for the great feature implementation and fast feedback!
